// import type { Metadata } from "next";

import ThemeProvider from "@/contexts/Theme";
import Dashboard from "@/components/templates/panel/Dashboard";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function PanelLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ThemeProvider>
      <div className="flex flex-col lg:flex-row gap-4 px-4 lg:px-10 py-6">
        <Dashboard />

        <main className="pt-4 lg:pt-6 w-full min-w-0">
          {children}
        </main>
      </div>
    </ThemeProvider>
  );
}
