// import type { Metadata } from "next";

import ThemeProvider from "@/contexts/Theme";
import Dashboard from "@/components/templates/panel/Dashboard";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function PanelLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ThemeProvider>
      <div className="px-2 md:px-0 mx-0 md:mx-10 flex gap-2 py-10">
        <Dashboard />

        <main className="pt-6 pr-8 w-full">
          {children}
        </main>
      </div>
    </ThemeProvider>
  );
}
