// import type { Metadata } from "next";

import FilterSection from "@/components/templates/learns/FilterSection";
import SortSection from "@/components/templates/learns/SortSection";
import ThemeProvider from "@/contexts/Theme";
import { Suspense } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function PanelLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ThemeProvider>
      <div className="px-2 md:px-0 mx-0 md:mx-10 flex flex-col gap-6 py-6">
        <h1 className="text-3xl text-main-100 font-lalezar mr-2 dark:text-white">همه دوره‌ها</h1>
        <div className="flex w-full h-full gap-4">
          <div className="hidden lg:block">
            <Suspense fallback={null}>
              <FilterSection />
            </Suspense>
          </div>

          <div className="flex flex-col w-full">
            <div className="hidden lg:block">
              <Suspense fallback={null}>
                <SortSection />
              </Suspense>
            </div>
            <main className="h-full">
              {children}
            </main>
          </div>
        </div>
        <div>
        </div>
      </div>
    </ThemeProvider>
  );
}
